pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '2.1.10'
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        maven { url 'https://repo1.maven.org/maven2/' }   //友盟
        maven { url 'https://maven.aliyun.com/repository/google/' }
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin/' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://developer.huawei.com/repo/' }
        maven { url 'https://jitpack.io' }
        mavenCentral()
    }
}

rootProject.name = "LearnAndroid"
include ':app'
include ':annotation'
include ':annotation_processor'
